<?php

namespace PHPSTORM_META;

// Generated by the yrewrite_domain_settings addon - do not edit by hand.
// Refreshed on cache:clear, or via "console domain-settings:ide-helper".

registerArgumentsSet('domain_settings_keys', 'aaa', 'area', 'demo_beschreibung', 'demo_kontakt_mail', 'demo_kontakt_name', 'demo_ort', 'demo_plz', 'demo_strasse', 'demo_titel', 'demo_untertitel', 'text');
expectedArguments(\FriendsOfRedaxo\DomainSettings\DomainSettings::get(), 0, argumentsSet('domain_settings_keys'));
