<?php

namespace PHPSTORM_META;

// Generated by the yrewrite_domain_settings addon - do not edit by hand.
// Refreshed on cache:clear, or via "console domain-settings:ide-helper".

registerArgumentsSet('domain_settings_keys', 'aaa', 'text');
expectedArguments(\FriendsOfRedaxo\DomainSettings\DomainSettings::get(), 0, argumentsSet('domain_settings_keys'));
