<?php

namespace PHPSTORM_META;

// Generated by the yrewrite_domain_settings addon - do not edit by hand.
// Refreshed on cache:clear, or via "console domain-settings:ide-helper".

registerArgumentsSet('domain_settings_keys', 'company_name', 'footer_text', 'test_bool', 'test_checkbox', 'test_color', 'test_date', 'test_datetime', 'test_link', 'test_linklist', 'test_media', 'test_medialist', 'test_radio', 'test_rgba', 'test_select', 'test_sql', 'test_text', 'test_textarea', 'test_time');
expectedArguments(\FriendsOfRedaxo\DomainSettings\DomainSettings::get(), 0, argumentsSet('domain_settings_keys'));
