language: php

php:
    - '7.2'

cache:
  directories:
  - $HOME/.composer/cache
  
before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    
script:
    - composer require --dev friendsofredaxo/linter
    - vendor/bin/rexlint
