package: yrewrite_domain_settings
version: '2.1.3'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/yrewrite_domain_settings
    
requires:
    redaxo: '^5.5'
    packages:
        yrewrite: '^2.5'
        yform: '>3.0, <5'
    php:
        version: '>=5.6'

page:
    hidden: true

pages:
    yrewrite/domain_settings:
        title: Domain Settings
        perm: yrewrite_domains[]

